id: IAEC87550
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T06:34:22+00:00'
last_modified: '2022-06-08T10:36:08.833215+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22299
  title: རྟ་རྒྱུག་རྒྱལ་འཇོག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    F0C0:
      image_group_id: I1KG17144
      title: ''
      total_pages: 194
      order: 1
      base_file: F0C0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
