id: P009380
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W22299
  title: རྟ་རྒྱུག་རྒྱལ་འཇོག
  author: ''
  volumes:
    93ac8a9486fb44ce918e13371251bcfd:
      image_group_id: I1KG17144
      title: ''
      volume_number: 1
      total_pages: 194
      base_file: v001.txt
